[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PRIVATE_TARGET = "server"

# Opt out of the Netlify image CDN
[build.processing]
  skip_processing = true

# Plugin to handle large environment variables
[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    include = ["FIREBASE_PRIVATE_KEY", "FIREBASE_ADMIN_PRIVATE_KEY"]

# These redirects ensure that all server-rendered pages are properly served
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# For client-side routing and to handle SSR paths
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true 