[build]
  command = "npm run netlify-build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Opt out of the Netlify image CDN
[build.processing]
  skip_processing = true

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Plugin to handle large environment variables
[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    include = ["FIREBASE_PRIVATE_KEY", "FIREBASE_ADMIN_PRIVATE_KEY"]

# Redirects for API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 